version: 2

before:
  hooks:
    - sh -c "cd ui && npm ci && npm run build"

builds:
  - id: corvo
    main: ./cmd/corvo
    binary: corvo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
        -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.Date}}

archives:
  - id: corvo
    name_template: "corvo_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - id: corvo-amd64
    ids: [corvo]
    goos: linux
    goarch: amd64
    dockerfile: deploy/Dockerfile.goreleaser
    image_templates:
      - "corvohq/corvo:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"

  - id: corvo-arm64
    ids: [corvo]
    goos: linux
    goarch: arm64
    dockerfile: deploy/Dockerfile.goreleaser
    image_templates:
      - "corvohq/corvo:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "corvohq/corvo:{{ .Version }}"
    image_templates:
      - "corvohq/corvo:{{ .Version }}-amd64"
      - "corvohq/corvo:{{ .Version }}-arm64"

  - name_template: "corvohq/corvo:latest"
    image_templates:
      - "corvohq/corvo:{{ .Version }}-amd64"
      - "corvohq/corvo:{{ .Version }}-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: corvohq
    name: corvo

brews:
  - name: corvo
    repository:
      owner: corvohq
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://corvohq.com"
    description: "Language-agnostic distributed job processing system"
    license: "MIT"
    install: |
      bin.install "corvo"
    test: |
      system "#{bin}/corvo", "--version"
